global:
  environment: staging
  namespace: cloudmart-staging

frontend:
  image:
    repository: "cloudmart-frontend-staging"

product:
  image:
    repository: "cloudmart-product-service-staging"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::779417963796:role/cloudmart-product-service-role-staging"

order:
  image:
    repository: "cloudmart-order-service-staging"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::779417963796:role/cloudmart-order-service-role-staging"

user:
  image:
    repository: "cloudmart-user-service-staging"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::779417963796:role/cloudmart-user-service-role-staging"

notification:
  image:
    repository: "cloudmart-notification-service-staging"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::779417963796:role/cloudmart-notification-service-role-staging"
