{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: {{ .Values.namespace | default "cloudmart-prod" }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.cloudConfig.awsRegion }}
      {{- if .Values.externalSecrets.secretStore.roleArn }}
      role: {{ .Values.externalSecrets.secretStore.roleArn }}
      {{- end }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.user.serviceAccount.name | default "user-service-sa" }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudmart-secrets
  namespace: {{ .Values.namespace | default "cloudmart-prod" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: cloudmart-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecretArn | default (printf "%s-db-credentials-%s" (default "cloudmart" .Values.global.project) .Values.global.environment) }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.dbSecretArn | default (printf "%s-db-credentials-%s" (default "cloudmart" .Values.global.project) .Values.global.environment) }}
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.jwtSecretArn | default (printf "%s-jwt-secret-%s" (default "cloudmart" .Values.global.project) .Values.global.environment) }}
{{- end -}}
