{{- if .Values.fargateLogging.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  labels:
    aws-observability: "enabled"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  flb_log_cw: "true"
  
  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match *frontend*
        region {{ .Values.cloudConfig.awsRegion }}
        log_group_name /cloudmart/frontend-{{ .Values.global.environment }}
        log_stream_prefix frontend-
        auto_create_group true

    [OUTPUT]
        Name cloudwatch_logs
        Match *product*
        region {{ .Values.cloudConfig.awsRegion }}
        log_group_name /cloudmart/product-service-{{ .Values.global.environment }}
        log_stream_prefix product-
        auto_create_group true

    [OUTPUT]
        Name cloudwatch_logs
        Match *order*
        region {{ .Values.cloudConfig.awsRegion }}
        log_group_name /cloudmart/order-service-{{ .Values.global.environment }}
        log_stream_prefix order-
        auto_create_group true

    [OUTPUT]
        Name cloudwatch_logs
        Match *user*
        region {{ .Values.cloudConfig.awsRegion }}
        log_group_name /cloudmart/user-service-{{ .Values.global.environment }}
        log_stream_prefix user-
        auto_create_group true

    [OUTPUT]
        Name cloudwatch_logs
        Match *notification*
        region {{ .Values.cloudConfig.awsRegion }}
        log_group_name /cloudmart/notification-service-{{ .Values.global.environment }}
        log_stream_prefix notification-
        auto_create_group true
{{- end }}
