{{- if not .Values.externalSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: cloudmart-secrets
  namespace: {{ .Values.namespace | default "cloudmart-prod" }}
type: Opaque
data:
  JWT_SECRET: {{ "local-dev-fallback-jwt-secret-key-32-chars-long" | b64enc | quote }}
  DB_USER: {{ "postgres" | b64enc | quote }}
  DB_PASSWORD: {{ "postgres" | b64enc | quote }}
{{- end -}}
