{{- if .Values.secretsStoreCSI.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.externalSecrets.dbSecretArn }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "DB_USER"
          - path: "password"
            objectAlias: "DB_PASSWORD"
      - objectName: "{{ .Values.externalSecrets.jwtSecretArn }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "JWT_SECRET"
            objectAlias: "JWT_SECRET"
  
  secretObjects:
    - secretName: {{ .Release.Name }}-secrets
      type: Opaque
      data:
        - key: DB_USER
          objectName: DB_USER
        - key: DB_PASSWORD
          objectName: DB_PASSWORD
        - key: JWT_SECRET
          objectName: JWT_SECRET
{{- end }}
