namespace: cloudmart-staging
global:
  environment: staging
  namespace: cloudmart-staging
  awsAccountId: "427712745475"
  registry: "427712745475.dkr.ecr.ap-south-1.amazonaws.com"
  xray:
    enabled: true
cloudConfig:
  awsRegion: "ap-south-1"
  dynamoDbTable: "cloudmart-products-staging"
  sqsQueueUrl: "https://sqs.ap-south-1.amazonaws.com/427712745475/cloudmart-order-events-staging"
  fromEmail: "noreply@cloudmart.example"
  dbHost: "cloudmart-postgres-staging.cjw4kaiiw5dg.ap-south-1.rds.amazonaws.com"
  dbPort: "5432"
  dbName: "cloudmart"
externalSecrets:
  enabled: true
  secretStore:
    roleArn: ""
  dbSecretArn: "arn:aws:secretsmanager:ap-south-1:427712745475:secret:cloudmart-db-credentials-staging-SvnViN"
  jwtSecretArn: "arn:aws:secretsmanager:ap-south-1:427712745475:secret:cloudmart-jwt-secret-staging-atthMP"
frontend:
  namespace: cloudmart-staging
  replicaCount: 1
  image:
    repository: "cloudmart-frontend-staging"
    tag: "bbf97b2-35"
  ingress:
    enabled: true
    className: "alb"
    annotations:
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/target-type: "ip"
      alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:ap-south-1:427712745475:regional/webacl/cloudmart-waf-web-acl-staging/3e4cd9da-efae-4f08-9214-1bf73cea9a51"
    hosts:
      - host: ""
        paths:
          - path: "/"
            pathType: "Prefix"
product:
  namespace: cloudmart-staging
  replicaCount: 1
  image:
    repository: "cloudmart-product-service-staging"
    tag: "bbf97b2-35"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::427712745475:role/cloudmart-product-service-role-staging"
order:
  namespace: cloudmart-staging
  replicaCount: 1
  image:
    repository: "cloudmart-order-service-staging"
    tag: "bbf97b2-35"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::427712745475:role/cloudmart-order-service-role-staging"
user:
  namespace: cloudmart-staging
  replicaCount: 1
  image:
    repository: "cloudmart-user-service-staging"
    tag: "bbf97b2-35"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::427712745475:role/cloudmart-user-service-role-staging"
notification:
  namespace: cloudmart-staging
  replicaCount: 1
  image:
    repository: "cloudmart-notification-service-staging"
    tag: "bbf97b2-35"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::427712745475:role/cloudmart-notification-service-role-staging"
  cloudConfig:
    awsRegion: "ap-south-1"
    sqsQueueUrl: "https://sqs.ap-south-1.amazonaws.com/427712745475/cloudmart-order-events-staging"
