apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudmart-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  PRODUCT_STORE_BACKEND: {{ .Values.config.productStoreBackend | quote }}
  PRODUCT_SERVICE_URL: "http://product-service:8001"
  ORDER_QUEUE_BACKEND: {{ .Values.config.orderQueueBackend | quote }}
  ORDER_SERVICE_URL: "http://order-service:8002"
  NOTIFICATION_QUEUE_BACKEND: {{ .Values.config.notificationQueueBackend | quote }}
  NOTIFICATION_EMAIL_BACKEND: {{ .Values.config.notificationEmailBackend | quote }}
  NOTIFICATION_POLL_INTERVAL: {{ .Values.config.notificationPollInterval | quote }}
  USER_DB_BACKEND: {{ .Values.config.userDbBackend | default "memory" | quote }}
